#!/usr/bin/env bash
# This bash script accept an ip address as an argument and
# Pings it 5 times

if [ $# -ne 1 ];
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
fi

ping -c 5 "$1"
