#!/usr/bin/env bash

# Function to handle SIGTERM and SIGQUIT signals
cleanup()
{
	echo "Deleting PID file and terminating script..."
	rm /var/run/myscript.pid
	exit 0
}

# Function to handle SIGINT signal
handle_sigint()
{
	echo "Y U no love me?!"
}

# Function to handle SIGTERM signal
handle_sigterm() 
{
	echo "I hate the kill command"
}

# Trap signals
trap 'cleanup' SIGQUIT SIGTERM
trap 'handle_sigint' SIGINT
trap 'handle_sigterm' SIGTERM

# Write PID to file
echo $$ > /var/run/myscript.pid

# Display messages indefinitely
while true; do
	echo "To infinity and beyond"
	sleep 1
done
