#!/usr/bin/env bash
# This script prints the contents of a directory in long format

for file in *; do
	if [[ -f "$file" && "$file" != -* ]]; then
		filename=$(echo "$file" | cut -d '-' -f 2-)
		echo "$filename"

	fi
done
