#!/usr/bin/env bash
# This bash script changes my local ip to a new asigned ip

cp /etc/hosts ~/hosts.new
sed -i 's/^127.0.0.1[[:space:]]*localhost$/127.0.0.1 localhost\n127.0.0.2 localhost/' ~/hosts.new
sed -i 's/^127.0.0.1[[:space:]]*localhost$/127.0.0.1 localhost\n127.0.0.2 localhost/; s/^.*facebook.com[[:space:]]*$/8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
