#!/usr/bin/env bash
# This bash script changes my local ip to a new asigned ip

sudo sed -i 's/^127.0.0.1.*/& 127.0.0.2/g' /etc/hosts
sudo sed -i 's/^.*facebook.com$/8.8.8.8 facebook.com/g' /etc/hosts
