#!/usr/bin/env bash
# This bash script changes my local ip to a new asigned ip

cp /etc/hosts ~/hosts.new
sed -i 's/^127.0.0.1.*/& 127.0.0.2/g' ~/hosts.new
sed -i 's/^.*facebook.com$/8.8.8.8 facebook.com/g' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
